[2025-03-31T21:14:33.933-0300] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: employee_changes_report.upload_to_s3 scheduled__2025-03-01T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
