[2025-03-31T21:15:02.987-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-31T21:15:02.991-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: employee_changes_report.load_and_clean_data scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-31T21:15:02.994-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: employee_changes_report.load_and_clean_data scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-31T21:15:02.994-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-03-31T21:15:02.998-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_and_clean_data> on 2025-03-01 00:00:00+00:00
[2025-03-31T21:15:03.001-0300] {standard_task_runner.py:63} INFO - Started process 11123 to run task
[2025-03-31T21:15:03.003-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'employee_changes_report', 'load_and_clean_data', 'scheduled__2025-03-01T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_new_dag.py', '--cfg-path', '/var/folders/pw/ybzcyby54d787c124gv_5tjw0000gn/T/tmpcu5vyg1n']
[2025-03-31T21:15:03.004-0300] {standard_task_runner.py:91} INFO - Job 8: Subtask load_and_clean_data
[2025-03-31T21:15:03.032-0300] {task_command.py:426} INFO - Running <TaskInstance: employee_changes_report.load_and_clean_data scheduled__2025-03-01T00:00:00+00:00 [running]> on host ordenador-portatil-de-user-2.local
[2025-03-31T21:15:03.055-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='employee_changes_report' AIRFLOW_CTX_TASK_ID='load_and_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T00:00:00+00:00'
[2025-03-31T21:15:03.055-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-31T21:15:05.898-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-31T21:15:05.899-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/Documents/repo test eng/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/user/Documents/repo test eng/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/user/Documents/repo test eng/env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/user/Documents/repo test eng/env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/Users/user/Documents/repo test eng/env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/user/Documents/repo test eng/airflow_data/dags/test_new_dag.py", line 43, in load_and_clean
    tables = Variable.get("TABLES", deserialize_json=True)
  File "/Users/user/Documents/repo test eng/env/lib/python3.10/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable TABLES does not exist'
[2025-03-31T21:15:05.906-0300] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=employee_changes_report, task_id=load_and_clean_data, execution_date=20250301T000000, start_date=20250401T001502, end_date=20250401T001505
[2025-03-31T21:15:05.914-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task load_and_clean_data ('Variable TABLES does not exist'; 11123)
[2025-03-31T21:15:05.933-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-31T21:15:05.940-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T21:15:05.941-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
